# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pr:
  - main

schedules:
- cron: '0 17 * * Sun-Fri'
  displayName: 'UI-TESTS SCHEDULED TRIGGER'
  branches:
    include:
      - main
  always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TestsChrome
  timeoutInMinutes: 15
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.22'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'Install packages'

    - script: npm run ui-tests-chrome
      displayName: 'UI-TESTS'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'reports/reportChrome.xml'

- job: TestsFirefox
  timeoutInMinutes: 15
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.22'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'Install packages'

    - script: npm run ui-tests-firefox
      displayName: 'UI-TESTS'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'reports/reportFirefox.xml'

- job: WorkItemCreation
  dependsOn:
  - TestsChrome
  - TestsFirefox
  condition: failed()
  steps:
    - bash: |
        az boards work-item create \
          --title "UI-tests failed while running build $(build.buildNumber)" \
          --type Task \
          --org https://dev.azure.com/kurganovkirill \
          -p "3 Project" \
          --assigned-to kurganovkirill2512
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
      displayName: 'Create work item on failure'
