# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pr:
  - main

pool:
  vmImage: "ubuntu-latest"

jobs:
- job: Build
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.22'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'Install packages'

    - script: npm run ui-tests
      displayName: 'UI-TESTS'

- job: 'Work item creation'
  dependsOn: Build
  condition: failed()
  steps:
    - bash: |
        az boards work-item create \
          --title "UI-tests in build $(build.buildNumber) failed" \
          --type Task \
          --detect true \
          -p 3 Project \
          --assigned-to kurganovkirill2512
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
      displayName: 'Create work item on failure'
